name = "abc-resolve"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "abc-resolve-db"
database_id = "00a24c68-825e-4a48-90c2-f01329310da5"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"
