export interface Option {
  id: string;
  label: string;
  value: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  multiSelect: boolean;
  options: Option[];
}

export const CATEGORIES: Category[] = [
  {
    id: "appearance",
    name: "Aparência",
    icon: "✨",
    description: "Cabelo, olhos, corpo e pele",
    multiSelect: true,
    options: [
      { id: "h1", label: "Cabelo longo loiro", value: "long blonde hair" },
      { id: "h2", label: "Cabelo longo moreno", value: "long dark brown hair" },
      { id: "h3", label: "Cabelo longo ruivo", value: "long red hair" },
      { id: "h4", label: "Cabelo curto preto", value: "short black hair" },
      { id: "h5", label: "Cacheado castanho", value: "curly chestnut brown hair" },
      { id: "h6", label: "Ondulado escuro", value: "wavy dark hair" },
      { id: "h7", label: "Platinado loiro", value: "platinum blonde hair" },
      { id: "h8", label: "Ombré colorido", value: "vibrant ombre hair" },
      { id: "e1", label: "Olhos castanhos", value: "expressive brown eyes" },
      { id: "e2", label: "Olhos azuis", value: "striking blue eyes" },
      { id: "e3", label: "Olhos verdes", value: "mesmerizing green eyes" },
      { id: "e4", label: "Olhos amendoados", value: "almond-shaped dark eyes" },
      { id: "b1", label: "Corpo esguio", value: "slender elegant figure" },
      { id: "b2", label: "Curvilínea hourglass", value: "curvy hourglass figure" },
      { id: "b3", label: "Atlética tonificada", value: "athletic toned physique" },
      { id: "b4", label: "Alta e esbelta", value: "tall statuesque figure" },
      { id: "b5", label: "Voluptuosa", value: "voluptuous full-figured body" },
      { id: "s1", label: "Pele clara", value: "fair porcelain skin" },
      { id: "s2", label: "Pele morena clara", value: "light tan skin" },
      { id: "s3", label: "Pele mediterrânea", value: "olive Mediterranean skin" },
      { id: "s4", label: "Pele negra", value: "beautiful dark brown skin" },
      { id: "s5", label: "Bronzeada", value: "bronzed sun-kissed skin" },
    ],
  },
  {
    id: "outfit",
    name: "Roupa",
    icon: "👗",
    description: "Vestimenta, lingerie e acessórios",
    multiSelect: true,
    options: [
      { id: "l1", label: "Lingerie rendada preta", value: "black lace lingerie set" },
      { id: "l2", label: "Lingerie rendada vermelha", value: "red lace lingerie set" },
      { id: "l3", label: "Sutiã e calcinha transparente", value: "sheer see-through lace bra and panty set" },
      { id: "l4", label: "Corpete de cetim", value: "satin corset with garter belt" },
      { id: "l5", label: "Body preto", value: "form-fitting black bodysuit" },
      { id: "l6", label: "Camisola de seda branca", value: "white silk negligee chemise" },
      { id: "l7", label: "Sutiã de renda e calcinha", value: "intricate lace bralette and panties" },
      { id: "t1", label: "Fio dental", value: "thong bikini bottom" },
      { id: "t2", label: "Biquíni triangular", value: "triangle string bikini" },
      { id: "t3", label: "Micro biquíni", value: "micro bikini barely-there" },
      { id: "t4", label: "Maiô decotado", value: "low-cut plunging one-piece swimsuit" },
      { id: "t5", label: "Biquíni de croché", value: "crocheted bikini handmade" },
      { id: "t6", label: "Biquíni de couro", value: "leather bikini" },
      { id: "a1", label: "Legging de couro", value: "tight leather leggings" },
      { id: "a2", label: "Legging estampada", value: "printed yoga leggings" },
      { id: "a3", label: "Legging metalizada", value: "metallic high-waist leggings" },
      { id: "a4", label: "Conjunto fitness", value: "athletic sports bra and compression leggings set" },
      { id: "a5", label: "Top cropped esportivo", value: "tight crop top sports bra" },
      { id: "a6", label: "Legging transparente", value: "sheer mesh leggings" },
      { id: "c1", label: "Vestido curto justo", value: "tight bodycon mini dress" },
      { id: "c2", label: "Shorts jeans curtinho", value: "cutoff denim micro shorts" },
      { id: "c3", label: "Vestido longo com fenda", value: "elegant long evening gown with thigh-high slit" },
      { id: "c4", label: "Vestido transparente", value: "sheer see-through overlay dress" },
      { id: "c5", label: "Vestido de couro", value: "tight leather mini dress" },
      { id: "c6", label: "Vestido off-shoulder", value: "off-shoulder wrap dress" },
      { id: "ac1", label: "Salto alto stiletto", value: "red-soled stiletto high heels" },
      { id: "ac2", label: "Botas até a coxa", value: "thigh-high leather boots" },
      { id: "ac3", label: "Meia-calça rendada", value: "lace thigh-high stockings" },
      { id: "ac4", label: "Joias douradas", value: "elegant gold jewelry and layered necklaces" },
      { id: "ac5", label: "Liga de coxa", value: "thigh garter belt" },
      { id: "ac6", label: "Óculos de sol", value: "fashionable sunglasses" },
    ],
  },
  {
    id: "pose",
    name: "Pose",
    icon: "💃",
    description: "Posição e ângulo do corpo",
    multiSelect: false,
    options: [
      { id: "p1", label: "De pé — de frente", value: "standing facing camera, full body shot from head to toe" },
      { id: "p2", label: "De costas, olhando por cima do ombro", value: "standing back to camera, looking over shoulder seductively, full body" },
      { id: "p3", label: "De lado — perfil completo", value: "standing side profile, full body visible" },
      { id: "p4", label: "Perfil ¾", value: "three-quarter view pose, full body" },
      { id: "p5", label: "Mãos no quadril", value: "standing with hands on hips, confident pose, full body" },
      { id: "p6", label: "Encostada na parede", value: "leaning against wall seductively, full body shot" },
      { id: "p7", label: "Sentada na cama", value: "sitting on bed with legs extended, full body visible" },
      { id: "p8", label: "Sentada na cadeira", value: "sitting on chair with legs elegantly crossed, full body visible" },
      { id: "p9", label: "Sentada no chão", value: "sitting on floor with knees bent, full body pose" },
      { id: "p10", label: "Deitada de costas", value: "lying on back facing camera, full body visible from head to toe" },
      { id: "p11", label: "Deitada de barriga", value: "lying on stomach, arching back, looking at camera, full body" },
      { id: "p12", label: "Deitada de lado", value: "lying on side, curves fully visible, full body shot" },
      { id: "p13", label: "Arqueando as costas", value: "arching back seductively, curves emphasized, full body" },
      { id: "p14", label: "Passando a mão no cabelo", value: "running hands through hair, looking at camera with intense gaze, full body" },
      { id: "p15", label: "Posando de joelhos", value: "kneeling pose, back arched, full body visible" },
      { id: "p16", label: "Caminhando de frente", value: "walking toward camera, full body shot, dynamic motion" },
    ],
  },
  {
    id: "location",
    name: "Cenário",
    icon: "🏖️",
    description: "Ambiente e local da foto",
    multiSelect: false,
    options: [
      { id: "loc1", label: "Quarto luxuoso", value: "luxurious master bedroom with silk sheets and dim romantic lighting" },
      { id: "loc2", label: "Estúdio profissional", value: "professional photography studio with seamless backdrop" },
      { id: "loc3", label: "Apartamento moderno", value: "modern luxury penthouse apartment living room" },
      { id: "loc4", label: "Banheiro com banheira", value: "elegant marble bathroom with clawfoot bathtub" },
      { id: "loc5", label: "Hotel de luxo", value: "five-star luxury hotel room with panoramic city view" },
      { id: "loc6", label: "Lounge com luz baixa", value: "dimly lit upscale lounge bar with elegant decor" },
      { id: "loc7", label: "Praia tropical ao pôr do sol", value: "tropical beach at golden sunset with ocean waves" },
      { id: "loc8", label: "Piscina privativa", value: "private infinity pool with palm trees and crystal blue water" },
      { id: "loc9", label: "Terraço com vista da cidade", value: "rooftop terrace with stunning panoramic city night lights" },
      { id: "loc10", label: "Jardim com flores", value: "lush blooming garden with colorful flowers and greenery" },
      { id: "loc11", label: "Rua urbana com neon", value: "urban street at night with vibrant neon lights" },
      { id: "loc12", label: "Villa mediterrânea", value: "Mediterranean villa terrace with sea view at sunset" },
      { id: "loc13", label: "Fundo branco de estúdio", value: "seamless pure white studio background" },
      { id: "loc14", label: "Fundo preto de estúdio", value: "solid black studio background" },
      { id: "loc15", label: "Fundo com fumaça", value: "smoky atmospheric studio with fog machine effect" },
      { id: "loc16", label: "Fundo bokeh colorido", value: "colorful bokeh light background, dreamy atmosphere" },
    ],
  },
  {
    id: "lighting",
    name: "Iluminação",
    icon: "💡",
    description: "Tipo e qualidade da luz",
    multiSelect: false,
    options: [
      { id: "li1", label: "Luz natural suave", value: "soft natural window light, gentle diffused shadows" },
      { id: "li2", label: "Hora dourada", value: "golden hour sunlight, warm amber and orange tones" },
      { id: "li3", label: "Estúdio profissional", value: "professional studio strobe lighting, even exposure" },
      { id: "li4", label: "Luz lateral dramática", value: "dramatic Rembrandt side lighting, strong defined shadows" },
      { id: "li5", label: "Contraluz/Silhueta", value: "backlit silhouette with rim lighting highlighting body curves" },
      { id: "li6", label: "Neon RGB vibrante", value: "vibrant colorful RGB neon ambient lighting, cyberpunk aesthetic" },
      { id: "li7", label: "Luz de vela íntima", value: "warm intimate candlelight glow, romantic atmosphere" },
      { id: "li8", label: "Chiaroscuro dramático", value: "chiaroscuro technique, extreme contrast between light and shadow" },
      { id: "li9", label: "Luz de borda nas curvas", value: "rim light accentuating body curves, dark moody background" },
      { id: "li10", label: "Luz difusa suave", value: "overcast diffused soft light, flattering even illumination" },
      { id: "li11", label: "Luz de néon azul", value: "cool blue neon lighting, cinematic atmosphere" },
      { id: "li12", label: "Flash editorial", value: "high fashion editorial strobe flash, high contrast" },
    ],
  },
  {
    id: "camera",
    name: "Câmera",
    icon: "📷",
    description: "Equipamento e configurações técnicas",
    multiSelect: true,
    options: [
      { id: "cam1", label: "Formato RAW", value: "RAW format unprocessed photography" },
      { id: "cam2", label: "Canon EOS R5", value: "shot on Canon EOS R5 mirrorless" },
      { id: "cam3", label: "Sony A7R IV", value: "shot on Sony A7R IV full-frame" },
      { id: "cam4", label: "Lente 85mm retrato", value: "85mm prime portrait lens" },
      { id: "cam5", label: "Lente 50mm", value: "50mm standard prime lens" },
      { id: "cam6", label: "Abertura f/1.4", value: "f/1.4 wide aperture, very shallow depth of field" },
      { id: "cam7", label: "8K ultra HD", value: "8K ultra high definition resolution" },
      { id: "cam8", label: "Hiper-realista", value: "hyperrealistic, ultra detailed skin texture and pores" },
      { id: "cam9", label: "Foco nítido", value: "tack sharp focus, crystal clear detail" },
      { id: "cam10", label: "Color grading cinematográfico", value: "professional cinematic color grading" },
      { id: "cam11", label: "Bokeh suave", value: "beautiful creamy bokeh background blur" },
      { id: "cam12", label: "Fotorrealista", value: "photorealistic rendering indistinguishable from real photography" },
    ],
  },
  {
    id: "style",
    name: "Estilo",
    icon: "🎨",
    description: "Estilo e atmosfera fotográfica",
    multiSelect: true,
    options: [
      { id: "st1", label: "Boudoir", value: "boudoir photography style, intimate and sensual" },
      { id: "st2", label: "Editorial de moda", value: "high fashion editorial photography" },
      { id: "st3", label: "Glamour", value: "glamour photography, polished and sophisticated" },
      { id: "st4", label: "Fitness", value: "fitness magazine photography style" },
      { id: "st5", label: "Praia / Verão", value: "beach summer photography vibes" },
      { id: "st6", label: "Haute Couture", value: "haute couture fashion photography" },
      { id: "st7", label: "Estética Vogue", value: "Vogue magazine aesthetic and composition" },
      { id: "st8", label: "Sensual e elegante", value: "sensual and elegant composition" },
      { id: "st9", label: "Vibrante e marcante", value: "bold and striking visual composition" },
      { id: "st10", label: "Romântico e suave", value: "soft romantic dreamy atmosphere" },
      { id: "st11", label: "Noir / Misterioso", value: "film noir mysterious moody aesthetic" },
      { id: "st12", label: "Futurista / Cyberpunk", value: "cyberpunk futuristic aesthetic" },
    ],
  },
];

export interface Preset {
  id: string;
  name: string;
  emoji: string;
  description: string;
  selections: Record<string, string[]>;
}

export const PRESETS: Preset[] = [
  {
    id: "boudoir",
    name: "Boudoir Clássico",
    emoji: "🌹",
    description: "Íntimo e sedutor com lingerie rendada",
    selections: {
      appearance: ["b2", "h1", "s2"],
      outfit: ["l1", "ac3", "ac5"],
      pose: ["p10"],
      location: ["loc1"],
      lighting: ["li7"],
      camera: ["cam1", "cam4", "cam7", "cam8", "cam9"],
      style: ["st1", "st8"],
    },
  },
  {
    id: "beach",
    name: "Praia Tropical",
    emoji: "🏖️",
    description: "Verão, sol e fio dental na praia",
    selections: {
      appearance: ["b1", "h1", "s5"],
      outfit: ["t1"],
      pose: ["p1"],
      location: ["loc7"],
      lighting: ["li2"],
      camera: ["cam1", "cam4", "cam7", "cam9", "cam12"],
      style: ["st5", "st3"],
    },
  },
  {
    id: "fitness",
    name: "Fitness Power",
    emoji: "💪",
    description: "Atlética e tonificada em legging",
    selections: {
      appearance: ["b3", "h2", "s2"],
      outfit: ["a4"],
      pose: ["p5"],
      location: ["loc2"],
      lighting: ["li3"],
      camera: ["cam1", "cam5", "cam7", "cam9"],
      style: ["st4"],
    },
  },
  {
    id: "neon",
    name: "Neon Urbano",
    emoji: "🌆",
    description: "Cyberpunk com luzes neon na cidade",
    selections: {
      appearance: ["b2", "h7", "s1"],
      outfit: ["c5", "ac1"],
      pose: ["p6"],
      location: ["loc11"],
      lighting: ["li6"],
      camera: ["cam1", "cam5", "cam7", "cam10", "cam11"],
      style: ["st9", "st12"],
    },
  },
  {
    id: "fashion",
    name: "Editorial Fashion",
    emoji: "👑",
    description: "Alta moda e sofisticação à beira-mar",
    selections: {
      appearance: ["b4", "h6", "s3"],
      outfit: ["c3", "ac1"],
      pose: ["p3"],
      location: ["loc12"],
      lighting: ["li4"],
      camera: ["cam1", "cam2", "cam4", "cam7", "cam12"],
      style: ["st6", "st7"],
    },
  },
  {
    id: "glamour",
    name: "Glamour Studio",
    emoji: "✨",
    description: "Polido e sofisticado com corpete",
    selections: {
      appearance: ["b2", "h1", "s1"],
      outfit: ["l4", "ac4", "ac3"],
      pose: ["p2"],
      location: ["loc14"],
      lighting: ["li9"],
      camera: ["cam1", "cam2", "cam4", "cam7", "cam8"],
      style: ["st3", "st7"],
    },
  },
];
